.Dd October 12, 2020
.Dt GS-SFTP 1
.Os
.Sh NAME
.Nm gs-sftp
.Nd Secure File Transfer Protocol via Global Socket.
.Sh SYNOPSIS
.Nm gs-sftp
.Op Fl lTR
.Op Fl s Ar secret
.Op Fl k Ar keyfile
.Sh DESCRIPTION
The
.Nm
utility is a wrapper script for gs-netcat. It allows two users to establish a secure SFTP connetion via the Global Socket Relay Network (GSRN). This is useful in a scenario where both users are behind NAT/Firewall and unable to connect to each other directly.
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl s Ar secret
A password chosen by the user. Both users need to use the same password to connect.
.It Fl k Ar FILE
A file containing the password.
.It Fl l
Server mode. The default mode is client.
.It Fl R
Places server (-l) into a read-only mode. Attempts to open files for writing, as well as other operations that change the state of the filesystem, will be denied.
.It Fl T
Use TOR. The
.Nm
tool will connect via TOR to the GSRN. This requires TOR to be installed and running. The IP and PORT of the TOR server can be set using environment variables.
.El
.Pp
See 
.Xr gs-netcat(1)
for more options.
.Sh EXAMPLES
.Nm Example 1
- SFTP Server listening for clients using password 'MySecret':
.Dl $ gs-sftp -s MySecret -l
.Pp
Connect sftp-client using the same password:
.Dl $ gs-sftp -s MySecret 
.Pp
.Sh ENVIRONMENT
See 
.Xr gs-netcat(1)
for a list of supported environment variables.
.Pp
.Sh SEE ALSO
.Xr gsocket(1) ,
.Xr gs-netcat(1) ,
.Xr sftp(1)
.Pp
.Sh BUGS
Efforts have been made to have
.Nm
"do the right thing" in all its various modes. If you believe that it is doing the wrong thing under whatever circumstances, please notify me (skyper@thc.org) and tell me how you think it should behave.
